//! Cline 格式 Hook 策略 — 每事件一个 PowerShell 脚本，位于配置的 hooks 目录

use std::fs;
use std::path::{Path, PathBuf};

use super::super::hook_installation_utils::{expand_path, get_hook_command};
use super::super::plugin_models::HookInstallationSpec;
use super::HookInstallationStrategy;

const GENERATED_MARKER: &str = "Auto-generated by CodeOrbit";

pub struct ClineHookStrategy;

impl ClineHookStrategy {
    fn resolve_hooks_directory(config_path: &str) -> PathBuf {
        let expanded = expand_path(config_path);
        let path = Path::new(&expanded);
        if path.extension().is_some() {
            path.parent()
                .map(Path::to_path_buf)
                .unwrap_or_else(|| PathBuf::from(&expanded))
        } else {
            PathBuf::from(&expanded)
        }
    }

    fn event_script_path(hooks_dir: &Path, event_name: &str) -> PathBuf {
        hooks_dir.join(format!("{event_name}.ps1"))
    }

    fn to_powershell_invocation(command: &str) -> String {
        if command.trim_start().starts_with('"') {
            format!("& {command}")
        } else {
            command.to_string()
        }
    }

    fn is_generated_codeorbit_script(content: &str, source_key: &str) -> bool {
        let lc = content.to_lowercase();
        lc.contains(&GENERATED_MARKER.to_lowercase())
            && (lc.contains("codeorbit.bridge")
                || lc.contains("codeorbit-bridge")
                || lc.contains(&format!("--source {source_key}").to_lowercase()))
    }
}

impl HookInstallationStrategy for ClineHookStrategy {
    fn install(&self, source_key: &str, spec: &HookInstallationSpec) -> bool {
        let hooks_dir = Self::resolve_hooks_directory(&spec.config_path);
        if fs::create_dir_all(&hooks_dir).is_err() {
            return false;
        }

        let command = Self::to_powershell_invocation(&get_hook_command(source_key));
        for event in &spec.events {
            let script_path = Self::event_script_path(&hooks_dir, event);
            let content = format!("# {GENERATED_MARKER}\n{command}");
            if fs::write(&script_path, content).is_err() {
                return false;
            }
        }
        true
    }

    fn uninstall(&self, source_key: &str, spec: &HookInstallationSpec) -> bool {
        let hooks_dir = Self::resolve_hooks_directory(&spec.config_path);
        if !hooks_dir.exists() {
            return true;
        }

        for event in &spec.events {
            let script_path = Self::event_script_path(&hooks_dir, event);
            if !script_path.exists() {
                continue;
            }
            if let Ok(content) = fs::read_to_string(&script_path)
                && Self::is_generated_codeorbit_script(&content, source_key)
            {
                let _ = fs::remove_file(&script_path);
            }
        }

        // 目录为空则删除
        if let Ok(mut entries) = fs::read_dir(&hooks_dir)
            && entries.next().is_none()
        {
            let _ = fs::remove_dir(&hooks_dir);
        }
        true
    }

    fn is_installed(&self, source_key: &str, spec: &HookInstallationSpec) -> bool {
        let hooks_dir = Self::resolve_hooks_directory(&spec.config_path);
        if !hooks_dir.exists() {
            return false;
        }
        spec.events.iter().any(|event| {
            let script_path = Self::event_script_path(&hooks_dir, event);
            script_path.exists()
                && fs::read_to_string(&script_path)
                    .map(|c| Self::is_generated_codeorbit_script(&c, source_key))
                    .unwrap_or(false)
        })
    }
}
